### ISSUE TITLE
Out of memory 

### ISSUE THREAD

**Issue by pentestb0x** [ron190/jsql-injection#37863]
I try to dump very larger data from table 15k rows.

I'm using Kali & Jsql v0.79

00:26:21,544 ERROR root:34 - Unhandled Exception on AWT-EventQueue-1
java.lang.OutOfMemoryError: Java heap space
	at javax.swing.text.GapContent.getChars(GapContent.java:213)
	at javax.swing.text.AbstractDocument.getText(AbstractDocument.java:810)
	at javax.swing.text.WrappedPlainView.loadText(WrappedPlainView.java:309)
	at javax.swing.text.WrappedPlainView.calculateBreakPosition(WrappedPlainView.java:235)
	at javax.swing.text.WrappedPlainView$WrappedLine.breakLines(WrappedPlainView.java:782)
	at javax.swing.text.WrappedPlainView$WrappedLine.update(WrappedPlainView.java:732)
	at javax.swing.text.WrappedPlainView$WrappedLine.insertUpdate(WrappedPlainView.java:723)
	at javax.swing.text.WrappedPlainView.insertUpdate(WrappedPlainView.java:470)
	at javax.swing.plaf.basic.BasicTextUI$RootView.insertUpdate(BasicTextUI.java:1610)
	at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.insertUpdate(BasicTextUI.java:1869)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.JTextArea.append(JTextArea.java:477)
	at com.jsql.view.swing.interaction.MessageChunk.execute(MessageChunk.java:46)
	at com.jsql.view.interaction.ObserverInteraction.update(ObserverInteraction.java:42)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at com.jsql.model.AbstractModelObservable.lambda$sendToViews$52(AbstractModelObservable.java:63)
	at com.jsql.model.AbstractModelObservable$$Lambda$90/1823541245.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
01:35:54,856 ERROR root:34 - Unhandled Exception on Image Animator 3
java.lang.OutOfMemoryError: Java heap space
	at sun.awt.image.GifImageDecoder.readImage(GifImageDecoder.java:470)
	at sun.awt.image.GifImageDecoder.produceImage(GifImageDecoder.java:212)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AWT-EventQueue-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Timer-0"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AWT-EventQueue-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AWT-XAWT"

**Comment by ron190** [comment]
The error `OutOfMemoryError: Java heap space` is either related to jSQL or your Java environment.

Actually jSQL uses only the GUI as a data interface, everything is displayed on screen even for large amount of data so it can surely lead to memory problems. Some work is planned to support correctly a lot of data, like pagination and writing result to a file, but for now you can try a few tips:

- Select only 2 or 3 columns instead of selecting a lot of columns before running the injection,
- You can obtain parts of the result without losing the data you've already processed if you stop the running task: right-click on the table that you are currently injecting and click on Stop, it will load the data already fetched.

It could be useful to start injection from a default row's number, like the 1001st row, or inject by block of 1000 rows. I think I'll implement this kind of feature too.

Also you can verify that your global environment is correctly sized:
- If you use a VM, like VirtualBox or VMWare, don't forget to allocate enough size to the base memory, like 1/4 of your RAM,
- Check your Java Heap size, if it's not sufficient it will generate OutOfMemoryError. On Windows run the command `java -XX:+PrintFlagsFinal -version | findstr /i "HeapSize PermSize ThreadStackSize"` to display your Java environment size (there are commands [for another OS](http://www.mkyong.com/java/find-out-your-java-heap-memory-size/)):
```
C:\Users\ron190>java -XX:+PrintFlagsFinal -version | findstr /i "HeapSize PermSize ThreadStackSize"

    uintx HeapSizePerGCThread                       = 67108864 {product}
    uintx InitialHeapSize                          := 16777216 {product}
    uintx LargePageHeapSizeThreshold                = 134217728 {product}
    uintx MaxHeapSize                              := 268435456 {product}
```

Usually you see results like mine `InitialHeapSize = 16777216 bytes`  (16M) and `MaxHeapSize = 268435456 bytes` (256M) which are the default settings that are very low. An application that is resource intensive should be better executed in an environment like `InitialHeapSize = 266634176 bytes`  (256M) and `MaxHeapSize = 4266146816 bytes` (4068M). 
Fortunately you can buff your Java environment settings when you load jSQL. Instead of loading `java -jar jsql-injection-v0.79.jar`, use in place `java -Xms512m -Xmx1024m -jar jsql-injection-v0.79.jar`, it will start the current application with a bigger Heap size and it should help you get the complete data.
