### ISSUE TITLE
Error at start

### ISSUE THREAD

**Issue by ghost** [ron190/jsql-injection#90379]
## What's the expected behavior?
When I start jsql-injection there is an exception:

21:18:14,732 ERROR root:35 - Unhandled Exception on main
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.jsql.model.injection.vendor.Vendor.<clinit>(Vendor.java:11)
	at com.jsql.model.InjectionModel.<init>(InjectionModel.java:121)
	at com.jsql.MainApplication.main(MainApplication.java:58)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 3 more

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"

And jsql-injection doesn't start. 

My OS: Arch Linux

**Comment by arslee07** [comment]
idk too

**Comment by ron190** [comment]
See #70695
