### ISSUE TITLE
Error When Starting jSql in Kali linux

### ISSUE THREAD

**Issue by Nethesh** [ron190/jsql-injection#90383]
$java -jar jsql-injection-v0.81.jar
 
07:16:47,449 ERROR root:35 - Unhandled Exception on main
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.jsql.model.injection.vendor.Vendor.<clinit>(Vendor.java:11)
	at com.jsql.model.InjectionModel.<init>(InjectionModel.java:121)
	at com.jsql.MainApplication.main(MainApplication.java:58)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 3 more

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"

**Comment by ron190** [comment]
See #70695
