### ISSUE TITLE
Jsql 0.84 / 0.85

### ISSUE THREAD

**Issue by pedrodj7878** [ron190/jsql-injection#95160]
Hi Ron,

I'm unable to run jsql 0.84 and 0.85 but the version 0.83 works.

java -jar jsql-injection-v0.85.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/jsql/MainApplication has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

Any idea?

Thank you

**Comment by ron190** [comment]
Sure, jsql requires Java 11 (version 55.0) since jsql v0.84.
As you use Java 8 (version 52.0) then you are limited to use jsql v0.83.
Just upgrade Java to at least Java 11 if you want to run jsql v0.84 and above.
