### ISSUE TITLE
 Incorrect or incomplete data

### ISSUE THREAD

**Issue by TannicArcher** [ron190/jsql-injection#95486]
[00:09:17,490] Boolean false positive, stopping...
[00:09:17,495] Fetching fails: no data to parse
[00:09:17,496] Incorrect metadata, response from site:
[00:09:17,497] >>>
[00:09:17,498] Incorrect or incomplete data: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.jsql.model.accessible.DataAccess.getDatabaseInfos(DataAccess.java:193) ~[jsql-injection-v0.92.jar:?]
	at com.jsql.model.InjectionModel.beginInjection(InjectionModel.java:218) ~[jsql-injection-v0.92.jar:?]
	at java.lang.Thread.run(Thread.java:1623) [?:?]

[00:09:17,499] Processing but failure is expected
[00:09:17,502] Извлечение баз данных
[00:09:39,642] Boolean false positive, stopping...
[00:09:39,656] Fetching fails: no data to parse
[00:09:39,657] Unexpected: No match while injecting databases

**Comment by ron190** [comment]
```
[00:09:17,490] Boolean false positive, stopping...
```
Host is unstable, look into the tab Boolean to confirm that characters sent by the host are incorrect.
Try to reduce the number of threads to see if connection improves.
