### ISSUE TITLE
Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by santicsls** [ron190/jsql-injection#95496]
Hi, this is a normal error? 

```
[11:26:50,501] Boolean false positive, stopping...
[11:26:50,514] Fetching fails: no data to parse
[11:26:50,514] Incorrect metadata, response from site:
[11:26:50,515] >>>
[11:26:50,515] Incorrect or incomplete data: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.jsql.model.accessible.DataAccess.getDatabaseInfos(DataAccess.java:193) ~[jsql-injection-v0.92.jar:?]
	at com.jsql.model.InjectionModel.beginInjection(InjectionModel.java:218) ~[jsql-injection-v0.92.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

[11:26:50,518] Processing but failure is expected
[11:26:50,519] Fetching databases...
[11:26:52,418] Boolean false positive, stopping...
[11:26:52,418] Fetching fails: no data to parse
[11:26:52,420] Unexpected: No match while injecting databases
```

**Comment by ron190** [comment]
More or less, yes... but message looks too verbose with the stacktrace, I'll see to make it shorter.

Here Boolean strategy has been confirmed but it seems unstable, you can try to reduce number of threads and disable metadata injection.
Also you may look at the logs to see if any part of the SQL is blocking the process and edit the query directly in SQL Engine.
